force-app/main/default/objects/Callout__c/Callout__c.object-meta.xml
<CustomObject>
    <label>Callout</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Callout Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Callouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Callout__c/fields/Related_Record__c.field-meta.xml
<CustomField>
    <fullName>Related_Record__c</fullName>
    <label>Related Record</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
/**
 * @description       : 
 * @author            : Chaminga Dissanayake
 * @group             : 
 * @last modified on  : 02-21-2021
 * @last modified by  : Chaminga Dissanayake
 * Modifications Log 
 * Ver   Date         Author                 Modification
 * 1.0   02-21-2021   Chaminga Dissanayake   Initial Version
**/
@isTest
public class TestDataFactory {
    public static Case createCase(String caseOrigin) {
        return new Case(Origin = caseOrigin);
    }

    public static Callout__c createCallout(Id jobId, Id relatedRecordId) {
        return new Callout__c(Job_Id__c = jobId, Related_Record__c = relatedRecordId);
    }
}